### ISSUE TITLE
Heat Recovery Ventilation system

### ISSUE THREAD

**Issue by robitmoh** [nagyrobi/home-assistant-configuration-examples#4]
Szia!

Szeretnék érdeklődni, hogy a szellőztető rendszer modbus protokolját hogy sikerült megszerezni?
Visszafejtetted, vagy "tűz" közelben vagy hozzá ?
Van egy Izzi rendszerem frissen beüzemelve ami csak 0-10V kontrollt tud hivatalosan  a vezérlője se wifis

Köszönöm
Tibor

**Comment by nagyrobi** [comment]
Szia!
A gyártóval vettem fel a kapcsolatot, aki megadta a MODBUS regiszterek listáját. A készüléz gyárilag egy saját, felhő alapú, külső vezérlőt adtak, annak helyére kötöttem az ESPHome-t. A belső vezérlőhöz nem nyúltam.
